### ISSUE TITLE
Unable to backup / restore from an AWS RDS Sql Server Instance

### ISSUE THREAD

**Issue by fwertz** [nvdweem/intellij-sqlserver-backup-restore#12]
Get the following timeout exception. I am able to connect / run queries in datagrip.

java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
	at dev.niels.sqlbackuprestore.ui.FileDialog$DatabaseFileSystem.getRoots(FileDialog.java:204)
	at dev.niels.sqlbackuprestore.ui.FileDialog.choose(FileDialog.java:55)
	at dev.niels.sqlbackuprestore.ui.FileDialog.chooseFile(FileDialog.java:50)
	at dev.niels.sqlbackuprestore.action.Restore.lambda$actionPerformed$1(Restore.java:55)
	at dev.niels.sqlbackuprestore.action.Restore.lambda$invokeAndWait$9(Restore.java:126)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by nvdweem** [comment]
I don't have access to an AWS RDS SQLServer instance but the line that triggered the error has been changed because it was also causing #11. You can try again with 0.8.0 but I'm not sure at all if it will work better or not.

**Comment by lohmanndouglas** [comment]
Hi, @nvdweem I had the trace from @fwertz using Azure RDS SQLServer

Plugin version: 0.8.0.
Driver: MICROSOFT JDBC DRIVER 9.1 FOR SQL SERVER

![image](https://user-images.githubusercontent.com/9731599/107210457-ed518480-69e2-11eb-8724-c3d9519f69b6.png)


``` java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
	at dev.niels.sqlbackuprestore.ui.SQLHelper.getDrives(SQLHelper.java:35)
	at dev.niels.sqlbackuprestore.ui.FileDialog$DatabaseFileSystem.getRoots(FileDialog.java:199)
	at dev.niels.sqlbackuprestore.ui.FileDialog.choose(FileDialog.java:56)
	at dev.niels.sqlbackuprestore.ui.FileDialog.chooseFile(FileDialog.java:51)
	at dev.niels.sqlbackuprestore.action.Backup.backup(Backup.java:58)
	at dev.niels.sqlbackuprestore.action.Backup.lambda$actionPerformed$0(Backup.java:33)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:324)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by nvdweem** [comment]
I created an AWS account and have an RDS SQLServer running. From what I can tell SSMS fails in pretty much all actions that are file based. My plugin currently does backups to and from files.

What the action is that you are trying to perform?
From what I can tell, SSMS can't backup RDS databases to disk but there is an option to backup to url. Are you trying to backup to a url (I'd have to figure out how that works though :))?

**Comment by lohmanndouglas** [comment]
Interesting, I did not know about URL backups. 

I am trying to do a file backup from a connection that is on Azure to a local file. 
I will study more about backups and connections on azure and SQLServer, I am new with these technologies :/

**Comment by nvdweem** [comment]
I have also not worked with SQL Server other than locally hosted servers. But I'm expecting that if Microsoft doesn't do file backups for cloud instances that I won't be able to make it work through a plugin either :).

I'll add a todo so that the next version mentions not being compatible with cloud instances. If there are other backup related things that SSMS is able to do that you want supported in the plugin I can look into those.
